### ISSUE TITLE
Massive hdfs access from global functions might break the Kerberos ticket

### ISSUE THREAD

**Issue by belldandyxtq** [pfnet/pfio#111]
**Problem Statement**
Massive calls to the `global functions`, such as `chainerio.open`, `chainerio.list`, to hdfs might break the Kerberos ticket, and cause the code to fail. **However, access from the handlers will cause the problem.**

**Examples of the Problem Code**
```
while True:
    # generating massive calls to chainerio.open
    # we have massive updaters inside
    with chainerio.open('hdfs:///user/README.txt', 'rb') as f:
            # fails after the ticket is broken
            f.read()
```

**Error Message**
```
20/03/17 11:51:51 WARN security.UserGroupInformation: Exception encountered while running the renewal command for xxxxxxx. (TGT end time:1584453111000, renewalFailures: 0, renewalFailuresTotal: 1)
ExitCodeException exitCode=1: kinit: Internal credentials cache error (filename: /tmp/krb5cc_xxxx) when 
initializing cache 

        at org.apache.hadoop.util.Shell.runCommand(Shell.java:1009)
        at org.apache.hadoop.util.Shell.run(Shell.java:902)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1227)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:1321)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:1303)
        at org.apache.hadoop.security.UserGroupInformation$TicketCacheRenewalRunnable.relogin(UserGroupI
nformation.java:1077)
        at org.apache.hadoop.security.UserGroupInformation$AutoRenewalForUserCredsRunnable.run(UserGroup
Information.java:988)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Root Cause**
Each Call to a global function, such as `chainerio.open`, `chainerio.list` creates an hdfs [handler ](https://github.com/chainer/chainerio/blob/faf6d8bb5ad10526436ede13375646f842e7890c/chainerio/filesystems/hdfs.py#L85) with a kerberos ticket [updater ](https://github.com/chainer/chainerio/blob/faf6d8bb5ad10526436ede13375646f842e7890c/chainerio/filesystems/hdfs.py#L123) inside, which runs in a separate thread and periodically updates the kerberos ticket cache. A massive calls results in a huge number of updater runs parallel. Moreover, the `java hadoop client` will also perform a sort of ticket update. The lack of race control among the updater can break the ticket data inside the `java hadoop client` and cause it to fail.

Currently, we still rely on our own ticket `updater`, it is because before `Hadoop 3.0` the `java hadoop client` cannot update the ticket from the keytab set though environment variable `KRB5_KTNAME`. 

**How to avoid**
Avoid using the global functions when you need to call it massively. Instead, create a handler

```
# one handler, one updater
hdfs_handler = chainerio.create_handler("hdfs")
while True:
    with handler.open('/user/README.txt', 'rb') as f:
         # will not fail
         f.read()
```

**Please NOTE: using handler CANNOT eliminate this issue, it can only significantly reduce the probability of having it by having only one updater instead of having massive updaters**

**Comment by kuenishi** [comment]
This is no longer an issue as krbticket was removed.
