### ISSUE TITLE
Opening a giant (exceeding 4GB~?) zip in S3 using `pfio.v2.from_url` raises "BadZipFile: Bad magic number for central directory"

### ISSUE THREAD

**Issue by belltailjp** [pfnet/pfio#239]
I noticed that opening a large zip file as a container using `from_url` api raises zip parse error.
It reproduced in both the following environment

- Ubuntu 18.04 with python 3.8, pfio==2.0.0
- 20.04 with py3.9, pfio==2.0.0

### Reproduction

Create random files and gather them into a zip, then put it in S3 bucket (I actually use our internal Ozone storage rather than S3, though).
```bash
$ N_FILES=4
$  for I in `seq -w 00 $N`; do
    echo $I
    dd if=/dev/urandom of=${I}.dat bs=1M count=1024
done
$ zip -0 dummy_data.zip *.dat
$ aws s3 cp dummy_data.zip s3://<bucket>/
```

```python
>>> import pfio
>>> pfio.v2.from_url('s3://<bucket>/dummy_data.zip')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pfio/v2/fs.py", line 347, in from_url
    fs = fs.open_zip(filename)
  File "/usr/local/lib/python3.8/site-packages/pfio/v2/fs.py", line 109, in open_zip
    return Zip(self, file_path, mode)
  File "/usr/local/lib/python3.8/site-packages/pfio/v2/zip.py", line 92, in __init__
    self.zipobj = zipfile.ZipFile(self.fileobj, mode)
  File "/usr/local/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.8/zipfile.py", line 1364, in _RealGetContents
    raise BadZipFile("Bad magic number for central directory")
zipfile.BadZipFile: Bad magic number for central directory
```

With `N_FILES=3` (ie., total size of the zip is 3GB), it's OK.

```python
>>> with pfio.v2.from_url('s3://<bucket>/dummy_data.zip') as fs:
...     print(list(fs.list()))
['00.dat', '01.dat', '02.dat']
```

#### Header
The error hits here https://github.com/python/cpython/blob/3.9/Lib/zipfile.py#L1352, meaning that the zip file header (first 4 bytes) is not expected.
However actually the file header is always the same regardless of `N_FILES` (=zip file size)
```
>>> with pfio.v2.open_url('s3://<bucket>/dummy_data.zip', 'rb') as f:
...     print(f.read(4))
b'PK\x03\x04'
```

#### Other filesystems
When opening these file from local filesystem, it has no problem. Same for HDFS. This seems to happen only to S3. 
```python
>>> with pfio.v2.from_url('/local/path/to/dummy_data.zip') as fs:
...     print(list(fs.list()))
['00.dat', '01.dat', '02.dat', '03.dat', '04.dat', '05.dat', '06.dat', '07.dat', '08.dat', '09.dat', '10.dat', '11.dat', '12.dat', '13.dat', '14.dat', '15.dat', '16.dat', '17.dat', '18.dat', '19.dat', '20.dat']
```

#### 4096MiB?

I made 3 1GiB files and one 1023MiB file that are then mixed up into an approximately 4095MiB zip file. With this zip it worked well.
```
>>> with pfio.v2.from_url('s3://<bucket>/dummy_data_4095mb.zip') as fs:
...     print(list(fs.list()))
... 
['00.dat', '01.dat', '02.dat', '1023MB.dat']
```
Seems like when the size of the zip exceeds exactly 4GiB, this issue happens.

**Comment by belltailjp** [comment]
It seems I found out the reason.
`_ObjectReader.seek` does not seem to handle `(0, os.SEEK_END)` (move the cursor to the last) not equivalently to other IO.

```python
print("Local filesystem")
with pfio.v2.open_url('/posix/path/to/dummy_data.zip', 'rb') as f:
    f.seek(0, 2)
    print(f.tell())
    f.seek(-100, 2)
    print(f.tell())

print("S3")
with pfio.v2.open_url('s3://<bucket>/dummy_data.zip', 'rb') as f:
    f.seek(0, 2)
    print(f.tell())
    f.seek(-100, 2)
    print(f.tell())
```

```
Local filesystem
22548581546
22548581446
S3
0
22548581446
```

If I modify as follows, it seems to work.
```
          elif whence in [2, io.SEEK_END]:
-             self.pos += pos
+             self.pos = self.content_length + pos
```
https://github.com/pfnet/pfio/blob/2.0.0/pfio/v2/s3.py#L126
